export const SET_COMPETITIONS   = 'setCompetitions'
export const DELETE_COMPETITION = 'deleteCompetition'
export const SET_CREATE_COMPETITION = 'setCreateCompetition'
export const CREATE_COMPETITION = 'createCompetition'
export const SET_COMPETITION = 'setCompetition'
export const SET_COMPETITION_PLAYERS = 'setCompetitionPlayers'