export const START_GAME = 'startGame'
export const SET_GAMES = 'setGames'
export const SET_WINNER = 'setWinner'
export const SET_CURRENT_GAME = 'setCurrentGame'
export const SHOW_FINISH_GAME_FORM = 'showFinishGameForm'
export const SET_FINISH_GAME = 'setFinishGame'
export const SET_GAME_HISTORY = 'setGameHistory'